from __future__ import annotations

from typing import Protocol

from domain.entities.chapter import Chapter
from domain.entities.edit_session import EditSession
from domain.entities.work import Work
from domain.entities.writing_assets import (
    CharacterProfile,
    ChapterOutline,
    Foreshadow,
    TimelineEvent,
    WorkOutline,
)


class WorkRepository(Protocol):
    def list_all(self) -> list[Work]: ...
    def find_by_id(self, work_id: str) -> Work | None: ...
    def save(self, work: Work) -> None: ...
    def delete(self, work_id: str) -> None: ...


class ChapterRepository(Protocol):
    def list_by_work(self, work_id: str) -> list[Chapter]: ...
    def find_by_id(self, chapter_id: str) -> Chapter | None: ...
    def save(self, chapter: Chapter) -> None: ...
    def save_many(self, chapters: list[Chapter]) -> None: ...
    def delete(self, chapter_id: str) -> None: ...


class EditSessionRepository(Protocol):
    def find_by_work_id(self, work_id: str) -> EditSession | None: ...
    def save(self, session: EditSession) -> None: ...


class WorkOutlineRepository(Protocol):
    def find_by_work(self, work_id: str) -> WorkOutline | None: ...
    def save(self, outline: WorkOutline) -> None: ...
    def clear_chapter_refs(self, work_id: str, chapter_id: str) -> None: ...
    def delete_by_work(self, work_id: str) -> None: ...


class ChapterOutlineRepository(Protocol):
    def find_by_chapter(self, chapter_id: str) -> ChapterOutline | None: ...
    def save(self, outline: ChapterOutline) -> None: ...
    def delete_by_chapter(self, chapter_id: str) -> None: ...
    def delete_by_work(self, work_id: str) -> None: ...


class TimelineEventRepository(Protocol):
    def list_by_work(self, work_id: str) -> list[TimelineEvent]: ...
    def find_by_id(self, event_id: str) -> TimelineEvent | None: ...
    def save(self, event: TimelineEvent) -> None: ...
    def delete(self, event_id: str) -> None: ...
    def reorder(self, work_id: str, mappings: list[dict]) -> list[TimelineEvent]: ...
    def clear_chapter_ref(self, chapter_id: str) -> None: ...
    def delete_by_work(self, work_id: str) -> None: ...


class ForeshadowRepository(Protocol):
    def list_by_work(self, work_id: str, status: str | None = None) -> list[Foreshadow]: ...
    def find_by_id(self, foreshadow_id: str) -> Foreshadow | None: ...
    def save(self, foreshadow: Foreshadow) -> None: ...
    def delete(self, foreshadow_id: str) -> None: ...
    def clear_chapter_ref(self, chapter_id: str) -> None: ...
    def delete_by_work(self, work_id: str) -> None: ...


class CharacterRepository(Protocol):
    def list_by_work(self, work_id: str, keyword: str = "") -> list[CharacterProfile]: ...
    def find_by_id(self, character_id: str) -> CharacterProfile | None: ...
    def save(self, character: CharacterProfile) -> None: ...
    def delete(self, character_id: str) -> None: ...
    def delete_by_work(self, work_id: str) -> None: ...
