from __future__ import annotations

from typing import Protocol

from domain.entities.chapter import Chapter
from domain.entities.edit_session import EditSession
from domain.entities.work import Work


class WorkRepository(Protocol):
    def list_all(self) -> list[Work]: ...
    def find_by_id(self, work_id: str) -> Work | None: ...
    def save(self, work: Work) -> None: ...
    def delete(self, work_id: str) -> None: ...


class ChapterRepository(Protocol):
    def list_by_work(self, work_id: str) -> list[Chapter]: ...
    def find_by_id(self, chapter_id: str) -> Chapter | None: ...
    def save(self, chapter: Chapter) -> None: ...
    def save_many(self, chapters: list[Chapter]) -> None: ...
    def delete(self, chapter_id: str) -> None: ...


class EditSessionRepository(Protocol):
    def find_by_work_id(self, work_id: str) -> EditSession | None: ...
    def save(self, session: EditSession) -> None: ...
