export const DEFAULT_BRANCH_COUNT = 4
export const DEFAULT_CHAPTER_COUNT = 3
export const DEFAULT_TARGET_WORDS = 2500
export const DEFAULT_RECENT_CHAPTER_LIMIT = 3
export const DEFAULT_LAST_CHAPTER_TAIL_CHARS = 500
