PROMPT_SECTION_CONTINUATION_RULES = "continuation_hard_rules"
PROMPT_SECTION_DETEMPLATE_RULES = "detemplate_hard_rules"
PROMPT_SECTION_DETEMPLATE_OPTIMIZATION = "detemplate_optimization_rules"
PROMPT_SECTION_TASK_GENERATION = "task_generation_rules"
PROMPT_SECTION_INTEGRITY_RULES = "integrity_check_rules"
PROMPT_SECTION_TITLE_RULES = "title_backfill_rules"

PROMPT_TYPE_CONTINUATION_MEMORY = "continuation_memory"
PROMPT_TYPE_CHAPTER_TASK = "chapter_task"
PROMPT_TYPE_STRUCTURAL_DRAFT = "structural_draft"
PROMPT_TYPE_DETEMPLATE = "detemplate"
PROMPT_TYPE_INTEGRITY_CHECK = "integrity_check"
PROMPT_TYPE_TITLE_BACKFILL = "title_backfill"

PROMPT_DEFAULT_RECENT_CHAPTERS = 3
PROMPT_DEFAULT_LAST_TAIL_MIN = 300
PROMPT_DEFAULT_LAST_TAIL_MAX = 800
PROMPT_DEFAULT_CHARACTER_LIMIT = 6
PROMPT_DEFAULT_FORESHADOW_LIMIT = 12

PLANNING_MODE_LIGHT = "light_planning"
PLANNING_MODE_DEEP = "deep_planning"

ARC_STAGE_SETUP = "setup"
ARC_STAGE_EARLY_PUSH = "early_push"
ARC_STAGE_ESCALATION = "escalation"
ARC_STAGE_CRISIS = "crisis"
ARC_STAGE_TURNING_POINT = "turning_point"
ARC_STAGE_PAYOFF = "payoff"
ARC_STAGE_AFTERMATH = "aftermath"

ARC_STAGE_ORDER = [
    ARC_STAGE_SETUP,
    ARC_STAGE_EARLY_PUSH,
    ARC_STAGE_ESCALATION,
    ARC_STAGE_CRISIS,
    ARC_STAGE_TURNING_POINT,
    ARC_STAGE_PAYOFF,
    ARC_STAGE_AFTERMATH,
]
