FORESHADOWING_ACTION_BURY = "bury"
FORESHADOWING_ACTION_ADVANCE = "advance"
FORESHADOWING_ACTION_RETRIEVE = "retrieve"
FORESHADOWING_ACTIONS = {
    FORESHADOWING_ACTION_BURY,
    FORESHADOWING_ACTION_ADVANCE,
    FORESHADOWING_ACTION_RETRIEVE,
}

HOOK_STRENGTH_WEAK = "weak"
HOOK_STRENGTH_MEDIUM = "medium"
HOOK_STRENGTH_STRONG = "strong"
HOOK_STRENGTHS = {
    HOOK_STRENGTH_WEAK,
    HOOK_STRENGTH_MEDIUM,
    HOOK_STRENGTH_STRONG,
}

CHAPTER_FUNCTION_CONTINUE_CRISIS = "continue_crisis"
CHAPTER_FUNCTION_ADVANCE_INVESTIGATION = "advance_investigation"
CHAPTER_FUNCTION_REVEAL_ABNORMAL = "reveal_abnormal"
CHAPTER_FUNCTION_RECOVER_FORESHADOW = "recover_foreshadow"
CHAPTER_FUNCTION_TRANSITION = "transition"
CHAPTER_FUNCTION_EXPLOSION = "explosion"

PACE_FAST = "fast"
PACE_SLOW_PRESSURE = "slow_pressure"
PACE_TRANSITION = "transition"
PACE_BURST = "burst"

GENERATION_STAGE_STRUCTURAL = "structural"
GENERATION_STAGE_DETEMPLATED = "detemplated"

STYLE_SOURCE_MANUAL = "manual"
STYLE_SOURCE_SAMPLE = "sample_extracted"
STYLE_SOURCE_HYBRID = "hybrid"

ORGANIZE_STAGE_PREPARE = "prepare"
ORGANIZE_STAGE_CHAPTER_ANALYSIS = "chapter_analysis"
ORGANIZE_STAGE_MEMORY_MERGE = "memory_merge"
ORGANIZE_STAGE_MEMORY_VIEW_BUILD = "memory_view_build"
ORGANIZE_STAGE_DONE = "done"

WRITING_STATUS_READY = "ready"
WRITING_STATUS_PENDING = "pending"
