from domain.constants.story_enums import (
    FORESHADOWING_ACTION_ADVANCE,
    HOOK_STRENGTH_MEDIUM,
    PACE_FAST,
)


CHAPTER_TITLE_FALLBACK_TEMPLATE = "第{chapter_number}章"
CONTINUATION_CONTEXT_RECENT_CHAPTER_LIMIT = 3
LAST_CHAPTER_TAIL_MIN_CHARS = 300
LAST_CHAPTER_TAIL_MAX_CHARS = 800
DEFAULT_LAST_CHAPTER_TAIL_CHARS = 500

DEFAULT_BRANCH_COUNT = 4
DEFAULT_TARGET_WORDS_PER_CHAPTER = 2500
DEFAULT_GENERATE_CHAPTER_COUNT = 3

DEFAULT_HOOK_STRENGTH = HOOK_STRENGTH_MEDIUM
DEFAULT_FORESHADOWING_ACTION = FORESHADOWING_ACTION_ADVANCE
DEFAULT_PACE_TARGET = PACE_FAST

DEFAULT_DIALOGUE_DENSITY = "medium"
DEFAULT_NARRATIVE_DISTANCE = "close"
DEFAULT_PREFERRED_RHYTHM = "dynamic"
