from abc import ABC, abstractmethod


class AnalysisMetricRepository(ABC):
    @abstractmethod
    def get(self,work_id: str,metric_type: str) -> dict[str,object] | None: ...
    @abstractmethod
    def save(self,work_id: str,metric_type: str,payload: dict[str,object],source_fingerprint: str,status: str="ready",error_code: str="") -> dict[str,object]: ...
    @abstractmethod
    def status(self,work_id: str) -> dict[str,object]: ...
    @abstractmethod
    def mark_stale(self,work_id: str,metric_types: list[str] | None=None) -> None: ...
