from __future__ import annotations

from abc import ABC, abstractmethod

from domain.entities.ai.opening_models import (
    OpeningBrief,
    OpeningDirection,
    OpeningDirectionBatch,
    OpeningDraftBatch,
    OpeningOriginalityReport,
    OpeningReferenceSession,
)


class OpeningRepository(ABC):
    @abstractmethod
    def save_brief(self, value: OpeningBrief) -> OpeningBrief: ...
    @abstractmethod
    def get_brief(self, brief_id: str) -> OpeningBrief | None: ...
    @abstractmethod
    def save_reference_session(self, value: OpeningReferenceSession) -> OpeningReferenceSession: ...
    @abstractmethod
    def get_reference_session(self, session_id: str) -> OpeningReferenceSession | None: ...
    @abstractmethod
    def list_reference_sessions(self, brief_id: str) -> list[OpeningReferenceSession]: ...
    @abstractmethod
    def save_direction_batch(self, value: OpeningDirectionBatch) -> OpeningDirectionBatch: ...
    @abstractmethod
    def get_direction_batch(self, batch_id: str) -> OpeningDirectionBatch | None: ...
    @abstractmethod
    def get_direction(self, direction_id: str) -> OpeningDirection | None: ...
    @abstractmethod
    def save_draft_batch(self, value: OpeningDraftBatch) -> OpeningDraftBatch: ...
    @abstractmethod
    def get_draft_batch(self, batch_id: str) -> OpeningDraftBatch | None: ...
    @abstractmethod
    def save_originality_report(self, value: OpeningOriginalityReport) -> OpeningOriginalityReport: ...
    @abstractmethod
    def find_by_idempotency(self, entity_type: str, idempotency_key: str): ...
    @abstractmethod
    def get_latest(self, work_id: str) -> dict[str, object]: ...

