from enum import Enum


class ModelRole(str, Enum):
    GLOBAL_ANALYSIS = "GLOBAL_ANALYSIS"
    CHAPTER_ANALYSIS = "CHAPTER_ANALYSIS"
    CONTINUATION_MEMORY_EXTRACTION = "CONTINUATION_MEMORY_EXTRACTION"
    PLOT_ARC_EXTRACTION = "PLOT_ARC_EXTRACTION"
    ARC_STATE_UPDATE = "ARC_STATE_UPDATE"
    ARC_SELECTION = "ARC_SELECTION"
    CHAPTER_PLANNING = "CHAPTER_PLANNING"
    CONSISTENCY_VALIDATION = "CONSISTENCY_VALIDATION"
    STRUCTURAL_WRITING = "STRUCTURAL_WRITING"
    CONTINUATION_WRITING = "CONTINUATION_WRITING"
    DETEMPLATING_REWRITE = "DETEMPLATING_REWRITE"
    STYLE_REWRITE = "STYLE_REWRITE"
    TITLE_BACKFILL = "TITLE_BACKFILL"
